ci: add a scenario for k3s

diff --git a/.github/workflows/plugins.yml b/.github/workflows/plugins.yml
--- a/.github/workflows/plugins.yml
+++ b/.github/workflows/plugins.yml
@@ -1,73 +1,149 @@
-name: "CI"
+name: CI
 on: [pull_request, push]
 jobs:
   kubectl-plugins-check-minikube:
     name: Validate from Minikube
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout kubectl-plugins repo
-      uses: actions/checkout@v1
-      with:
-        repository: exxocism/kubectl-plugins
-        ref: ${{ github.head_ref }}
+      - name: Checkout kubectl-plugins repo
+        uses: actions/checkout@v1
+        with:
+          repository: exxocism/kubectl-plugins
+          ref: ${{ github.head_ref }}
 
-    - name: Install dependencies - conntrack, zsh
-      run: sudo apt-get update && sudo apt-get install -y conntrack zsh
+      - name: Install dependencies - conntrack, zsh
+        run: sudo apt-get update && sudo apt-get install -y conntrack zsh
 
-    - name: Setup Minikube
-      id: minikube
-      uses: medyagh/setup-minikube@v0.0.18
+      - name: Setup Minikube
+        id: minikube
+        uses: medyagh/setup-minikube@v0.0.18
 
-    - name: Sanity Check
-      run: kubectl get pods -nkube-system && (printf "\n\u2705[PASS] Sanity Check (get pods)\n") || (printf "\n\u274c [FAIL] Unable to retrieve pod list.\n" && exit 1)
+      - name: Sanity Check
+        shell: zsh -l {0}
+        run: kubectl get pods -nkube-system && (printf "\n\u2705[PASS] Sanity Check (get pods)\n") || (printf "\n\u274c [FAIL] Unable to retrieve pod list.\n" && exit 1)
 
-    - name: Install plugins
-      shell: zsh -l {0}
-      run: |  
-        cd ../kubectl-plugins
-        ./install-plugins.sh
-        kubectl config set-context $(kubectl config current-context) --namespace=kube-system && (printf "\n\u2705[PASS] Installation Script.\n") || (printf "\n\u274c [FAIL] Installation error\n" && exit 1)
+      - name: Install plugins
+        shell: zsh -l {0}
+        run: |
+          cd ../kubectl-plugins
+          ./install-plugins.sh
+          kubectl config set-context $(kubectl config current-context) --namespace=kube-system && (printf "\n\u2705[PASS] Installation Script.\n") || (printf "\n\u274c [FAIL] Installation error\n" && exit 1)
 
-    - name: kubectl switch
-      shell: zsh -l {0}
-      run: |
-        kubectl switch default
-        [ $? -eq 0 ] && (printf "\n\u2705 [PASS] Switched to default namespace.\n") ||  (printf "\n\u274c [FAIL] Failed switching namespace.\n" && exit 1)
+      - name: kubectl switch
+        shell: zsh -l {0}
+        run: |
+          kubectl switch default
+          [ $? -eq 0 ] && (printf "\n\u2705 [PASS] Switched to default namespace.\n") ||  (printf "\n\u274c [FAIL] Failed switching namespace.\n" && exit 1)
 
+      - name: kubectl ssh
+        shell: zsh -l {0}
+        run: |
+          kubectl run test --restart=Never --image=debian --command=true -- sleep 300
+          sleep 10
+          # Grant shell login for games user
+          kubectl exec test -- usermod -s /bin/sh games
+          # Necessary changes without attached tty
+          sed -i 's|"-it",||g' $(which kubectl-ssh)
+          sed -i 's| -it | --attach=true |g' $(which kubectl-ssh)
+          sed -i 's|"tty": true|"tty": false|g' $(which kubectl-ssh)
+          sed -i 's|"stdin": true|"stdin": false|g' $(which kubectl-ssh)
+          sed -i 's|"stdinOnce": true|"stdinOnce": false|g' $(which kubectl-ssh)
+          if [[ $(kubectl ssh -u games test -- whoami | tail -n1) == "games" ]]; then 
+            printf "\n\u2705 Successfully logged in as games user.\n"
+          else
+            printf "\n\u274c Unable to login as games user.\n"
+            exit 1
+          fi
 
-    - name: kubectl ssh
-      shell: zsh -l {0}
-      run: |
-        kubectl run test --restart=Never --image=debian --command=true -- sleep 300
-        sleep 10
-        # Grant shell login for games user
-        kubectl exec test -- usermod -s /bin/sh games
-        # Necessary changes without attached tty
-        sed -i 's|"-it",||g' $(which kubectl-ssh)
-        sed -i 's| -it | --attach=true |g' $(which kubectl-ssh)
-        sed -i 's|"tty": true|"tty": false|g' $(which kubectl-ssh)
-        sed -i 's|"stdin": true|"stdin": false|g' $(which kubectl-ssh)
-        sed -i 's|"stdinOnce": true|"stdinOnce": false|g' $(which kubectl-ssh)
-        if [[ $(kubectl ssh -u games test -- whoami | tail -n1) == "games" ]]; then 
-          printf "\n\u2705 Successfully logged in as games user.\n"
-        else
-          printf "\n\u274c Unable to login as games user.\n"
-          exit 1
-        fi
-        
-    - name: kubectl uptime
-      shell: zsh -l {0}
-      run: |
-        sudo apt update; sudo apt install -y ruby
-        kubectl uptime && (printf "\n\u2705[PASS] Uptime Ran\n") || (printf "\n\u274c [FAIL] Uptime plugin failure\n" && exit 1)
+      - name: kubectl uptime
+        shell: zsh -l {0}
+        run: |
+          sudo apt update; sudo apt install -y ruby
+          kubectl uptime && (printf "\n\u2705[PASS] Uptime Ran\n") || (printf "\n\u274c [FAIL] Uptime plugin failure\n" && exit 1)
 
-    - name: kubectl prompt
-      shell: zsh -l {0}
-      run: |
-        # Interactive input required. Just validate the help prompt.
-        kubectl prompt --help && (printf "\n\u2705[PASS] Validated -h on prompt\n") || (printf "\n\u274c [FAIL] Prompt plugin: Unexpected output.\n" && exit 1)
+      - name: kubectl prompt
+        shell: zsh -l {0}
+        run: |
+          # Interactive input required. Just validate the help prompt.
+          kubectl prompt --help && (printf "\n\u2705[PASS] Validated -h on prompt\n") || (printf "\n\u274c [FAIL] Prompt plugin: Unexpected output.\n" && exit 1)
 
-    - name: kubectl image
-      shell: zsh -l {0}
-      run: |
-        kubectl image -p -i kafka && (printf "\n\u2705[PASS] Returned Public Images\n") || (printf "\n\u274c [FAIL] Unable to retrieve list from Docker registry." && exit 1)
+      - name: kubectl image
+        shell: zsh -l {0}
+        run: |
+          kubectl image -p -i kafka && (printf "\n\u2705[PASS] Returned Public Images\n") || (printf "\n\u274c [FAIL] Unable to retrieve list from Docker registry." && exit 1)
+
+  kubectl-plugins-check-k3s:
+    name: Validate from k3s containerd
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout kubectl-plugins repo
+        uses: actions/checkout@v1
+        with:
+          repository: exxocism/kubectl-plugins
+          ref: ${{ github.head_ref }}
+
+      - name: Install dependencies - zsh
+        run: sudo apt-get update && sudo apt-get install -y zsh
+
+      - name: Setup k3s
+        shell: zsh -l {0}
+        run: |
+          curl -sfL https://get.k3s.io | sh -s -
+          export KUBECONFIG="/home/runner/.kube/config"
+          echo "export KUBECONFIG=/home/runner/.kube/config" >> /home/runner/.zprofile
+          mkdir /home/runner/.kube 2> /dev/null
+          sudo k3s kubectl config view --raw > "$KUBECONFIG"
+          chmod 600 "$KUBECONFIG"
+
+      - name: Sanity Check
+        shell: zsh -l {0}
+        run: |
+          sleep 30
+          kubectl get pods -nkube-system && (printf "\n\u2705[PASS] Sanity Check (get pods)\n") || (printf "\n\u274c [FAIL] Unable to retrieve pod list.\n" && exit 1)
+
+      - name: Install plugins
+        shell: zsh -l {0}
+        run: |
+          cd ../kubectl-plugins
+          ./install-plugins.sh
+          source /home/runner/.zprofile
+          kubectl config set-context $(kubectl config current-context) --namespace=kube-system && (printf "\n\u2705[PASS] Installation Script.\n") || (printf "\n\u274c [FAIL] Installation error\n" && exit 1)
+
+      - name: kubectl switch
+        shell: zsh -l {0}
+        run: |
+          kubectl switch default
+          [ $? -eq 0 ] && (printf "\n\u2705 [PASS] Switched to default namespace.\n") ||  (printf "\n\u274c [FAIL] Failed switching namespace.\n" && exit 1)
+
+      - name: kubectl ssh
+        shell: zsh -l {0}
+        run: |
+          kubectl run test --restart=Never --image=debian --command=true -- sleep 500
+          sleep 20
+          # Grant shell login for games user
+          kubectl exec test -- usermod -s /bin/sh games
+          sleep 10
+          RESULT=$(kubectl ssh -u games test -- whoami | grep 'games' | tail -n1 | tr -d '\r')
+          if [[ $RESULT == "games" ]]; then 
+            printf "\n\u2705 Successfully logged in as games user.\n"
+          else
+            printf "\n\u274c Unable to login as games user.\n"
+            exit 1
+          fi
+
+      - name: kubectl uptime
+        shell: zsh -l {0}
+        run: |
+          sudo apt update; sudo apt install -y ruby
+          kubectl uptime && (printf "\n\u2705[PASS] Uptime Ran\n") || (printf "\n\u274c [FAIL] Uptime plugin failure\n" && exit 1)
+
+      - name: kubectl prompt
+        shell: zsh -l {0}
+        run: |
+          # Interactive input required. Just validate the help prompt.
+          kubectl prompt --help && (printf "\n\u2705[PASS] Validated -h on prompt\n") || (printf "\n\u274c [FAIL] Prompt plugin: Unexpected output.\n" && exit 1)
+
+      - name: kubectl image
+        shell: zsh -l {0}
+        run: |
+          kubectl image -p -i kafka && (printf "\n\u2705[PASS] Returned Public Images\n") || (printf "\n\u274c [FAIL] Unable to retrieve list from Docker registry." && exit 1)
